spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
server:
  port: 8081